Repository ampproject/amp-toolbox, pull requests merged in 2019-10, with the labels that each got.

#519 fixes include examples to use toolbox-cache-url
  packages/cache-url/README.md
Labels: cla: yes

#516 optimizer: Cleanup linter hints in README
  packages/optimizer/README.md
Labels: cla: yes

#522 Remove dependency on pika
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  packages/linter/.gitignore
  packages/linter/README.md
  packages/linter/package.json
  packages/linter/tests/lib.ts
  packages/linter/tsconfig.json
Labels: cla: yes

#517 optimizer: Do not append rtv/{rtv}/ to ampUrlPrefix
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_excludes_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_excludes_version/input.html
Labels: bug, cla: yes

#518 optimizer: Make dynamic component URL rewrites optional
  packages/optimizer/README.md
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_with_rtv/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_with_rtv/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_without_rtv/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_without_rtv/input.html
Labels: cla: yes, enhancement

#527 Fix: dont' fail optimizer if inline amp-script is empty
  packages/optimizer/lib/transformers/AmpScriptCsp.js
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/ignores_empty_scripts/expected_output.html
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/ignores_empty_scripts/input.html
Labels: cla: yes

#524 run tests before push
  package-lock.json
  package.json
  packages/linter/package.json
Labels: cla: yes
