Repository ampproject/amp-toolbox, pull requests merged in 2019-07, with the labels that each got.

#374 Detect inline bookend data
  packages/linter/src/rules/BookendExists.ts
  packages/linter/tests/local.ts
  packages/linter/tests/local/BookendExists-1/source.html
  packages/linter/tests/local/BookendExists-2/source.html
  packages/linter/tests/local/BookendExists-3/source.html
Labels: cla: yes

#377 Create amp-validator-rules package
  README.md
  package-lock.json
  package.json
  packages/validator-rules/.gitignore
  packages/validator-rules/README.md
  packages/validator-rules/index.js
  packages/validator-rules/lib/AmpValidatorRules.js
  packages/validator-rules/lib/loadRules.js
  packages/validator-rules/package.json
  packages/validator-rules/spec/AmpValidatorRulesSpec.js
Labels: cla: yes

#385 update dependencies
  package-lock.json
  package.json
  packages/linter/package.json
  packages/optimizer/spec/helpers/reporter.js
Labels: cla: yes

#389 Replace oneBehindFetch with cross-fetch in validator-rules
  package-lock.json
  packages/validator-rules/lib/loadRules.js
  packages/validator-rules/package.json
Labels: cla: yes

#390 Ensure meta chartset is first element in head
  packages/optimizer/lib/transformers/ReorderHeadTransformer.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.valid.html
  packages/optimizer/spec/transformers/valid/ReorderHeadTransformer/reorders_head_amphtml/expected_output.html
Labels: cla: yes

#402 Fix setup
  .travis.yml
  README.md
  package-lock.json
  package.json
  packages/cli/spec/cmds/lintSpec.js
  packages/linter/package.json
  packages/linter/src/cli.ts
Labels: cla: yes

#403 Transformed self
  package-lock.json
  package.json
  packages/optimizer/lib/transformers/AddTransformedFlag.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.valid.html
  packages/optimizer/spec/valid-amp/ValidAmpSpec.js
Labels: cla: yes

#405 Remove AMP-Access-Control-Allow-Source-Origin
  packages/cors/README.md
  packages/cors/lib/cors.js
  packages/cors/spec/lib/corsSpec.js
Labels: cla: yes, enhancement

#416 Parse dump-signedexchange's JSON output
  packages/linter/src/rules/SxgDumpSignedExchangeVerify.ts
Labels: cla: yes

#423 Fix wording of sxg forwarding test
  packages/linter/src/rules/SxgAmppkgIsForwarded.ts
Labels: cla: yes

#422 Run prettier over packages/linter
  package.json
Labels: cla: yes

#424 typo
  packages/optimizer/README.md
Labels: cla: no

#420 amp lint now supports same features as amplint
  package.json
  packages/cli/lib/cli.js
  packages/cli/lib/cmds/lint.js
  packages/cli/spec/cmds/lintSpec.js
  packages/cli/spec/helpers/MockLogger.js
  packages/core/lib/Log.js
  packages/linter/src/cli.ts
  packages/linter/src/rules/SxgDumpSignedExchangeVerify.ts
Labels: cla: yes, enhancement, toolbox-linter
