Repository ampproject/amp-toolbox, pull requests merged in 2019-08, with the labels that each got.

#430 support AMP Email Cors
  package-lock.json
  packages/cache-list/package.json
  packages/cache-url/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/cors/README.md
  packages/cors/lib/cors.js
  packages/cors/package.json
  packages/cors/spec/lib/corsSpec.js
  packages/linter/package.json
  packages/optimizer-express/package.json
  packages/optimizer/package.json
  packages/runtime-version/package.json
  packages/update-cache/package.json
  packages/validator-rules/package.json
Labels: cla: yes

#440 Improve dump-signedexchange tests
  packages/linter/src/rules/SxgContentNegotiationIsOk.ts
  packages/linter/src/rules/SxgDumpSignedExchangeVerify.ts
Labels: cla: yes

#450 explain when boilerplate cannot be removed
  packages/optimizer/README.md
Labels: cla: yes

#454 Add log.success() fn
  packages/core/lib/Log.js
Labels: bug, cla: yes

#464 Add script-csp toolbox package
  README.md
  package-lock.json
  package.json
  packages/script-csp/README.md
  packages/script-csp/index.js
  packages/script-csp/lib/calculateHash.js
  packages/script-csp/package.json
  packages/script-csp/spec/calculateHashSpec.js
Labels: cla: yes, enhancement, toolbox-script-csp

#465 Add AmpScriptCsp optimizer
  packages/optimizer/README.md
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/transformers/AmpScriptCsp.js
  packages/optimizer/package.json
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/adds_correct_hashes/expected_output.html
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/adds_correct_hashes/input.html
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/appends_existing_meta/expected_output.html
  packages/optimizer/spec/transformers/valid/AmpScriptCsp/appends_existing_meta/input.html
Labels: cla: yes, enhancement, toolbox-optimizer

#467 Keyframes transformer
  packages/optimizer/lib/transformers/SeparateKeyframes.js
  packages/optimizer/spec/end-to-end/EndToEndSpec.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.valid.html
  packages/optimizer/spec/transformers/valid/SeparateKeyframes/doesnt_add_tag_with_no_keyframes/expected_output.html
Labels: cla: yes

#469 Changelog
  CHANGELOG.md
  package-lock.json
  package.json
  packages/cache-list/package.json
  packages/cache-url/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/cors/package.json
  packages/linter/package.json
  packages/optimizer-express/package.json
  packages/optimizer/package.json
  packages/runtime-version/package.json
  packages/script-csp/package.json
  packages/update-cache/package.json
  packages/validator-rules/package.json
Labels: cla: yes
