Repository ampproject/amp-toolbox, pull requests merged in 2020-01, with the labels that each got.

#542 Remove AMP-Redirect-To from access-control-expose-headers for email
  packages/cors/lib/cors.js
Labels: cla: yes, enhancement

#568 Adds "repository" and "homepage" to every package.json
  packages/cache-list/package.json
  packages/cache-url/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/cors/package.json
  packages/lighthouse-plugin-amp/package.json
  packages/linter/package.json
  packages/optimizer-express/package.json
  packages/optimizer/package.json
  packages/runtime-version/package.json
  packages/script-csp/package.json
  packages/update-cache/package.json
  packages/validator-rules/package.json
Labels: cla: yes

#569 Add AutoExtensionImporter
  package-lock.json
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/RuntimeHostHelper.js
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/package.json
  packages/optimizer/spec/transformers/TransformerSpec.js
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-bindX/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-bindX/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-data-amp-bind/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-data-amp-bind/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-square-brackets/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-bind-square-brackets/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/auto-imports-missing-extensions/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/auto-imports-missing-extensions/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/ignores-existing-extensions/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/ignores-existing-extensions/input.html
Labels: cla: yes

#570 update dependencies
  package-lock.json
  package.json
  packages/linter/package.json
  packages/optimizer-express/package.json
Labels: cla: yes

#573 Auto inject missing AMP boilerplate
  packages/cli/spec/cmds/optimizeSpec.js
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/TreeParser.js
  packages/optimizer/lib/transformers/AddMandatoryTags.js
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/adds-missing-tags/expected_output.html
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/adds-missing-tags/input.html
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/keeps-existing-tags/expected_output.html
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/keeps-existing-tags/input.html
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/turns-empty-file-into-valid-amp-doc/expected_output.html
  packages/optimizer/spec/transformers/valid/AddMandatoryTags/turns-empty-file-into-valid-amp-doc/input.html
Labels: cla: yes

#580 Fix: ReorderHead priorities
  packages/optimizer/lib/transformers/ReorderHeadTransformer.js
  packages/optimizer/spec/transformers/valid/ReorderHeadTransformer/optimize_move_resource_hints_top/expected_output.html
  packages/optimizer/spec/transformers/valid/ReorderHeadTransformer/reorders_head_amphtml/expected_output.html
Labels: bug, cla: yes, toolbox-optimizer

#581 Fix: Empty <amp-experiment> blocks boilerplate removal
  packages/optimizer/lib/transformers/ServerSideRendering.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/adds_i_amphtml_layout_attribute/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/adds_i_amphtml_layout_attribute/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp_experiment_present/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp_experiment_present/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp_experiment_present/input.html /input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_empty/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_empty/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_invalid_json/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_invalid_json/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_no_tag/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_removed_when_amp_experiment_present_but_no_tag/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_then_script_not_removed_due_to_script/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_transform_amp_audio/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_transform_amp_audio/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/removes_amp_boilerplate/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/removes_amp_boilerplate/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/test.sh
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_fixed_height/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_fixed_height/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_height/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_height/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_width/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_width/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_width_and_height/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/transforms_layout_flex_item_with_width_and_height/input.html
Labels: bug, cla: yes, toolbox-optimizer

#588 Add MinifyHtml transformer
  CHANGELOG.md
  package-lock.json
  packages/core/package.json
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/transformers/MinifyHtml.js
  packages/optimizer/lib/transformers/PreloadImages.js
  packages/optimizer/lib/transformers/SeparateKeyframes.js
  packages/optimizer/package-lock.json
  packages/optimizer/package.json
  packages/optimizer/spec/end-to-end/body-only/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/helpers/TransformerRunner.js
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_comments/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_comments/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_unneeded_whitespace/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_unneeded_whitespace/input.html
  packages/optimizer/spec/valid-amp/files/Joining_Analytics_Sessions.html
Labels: cla: yes, enhancement, toolbox-optimizer

#590 AutoExtensionImporter: fix amp-carousel adding amp-lightbox-gallery
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-carousel/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-carousel/input.html
Labels: cla: yes

#591 Only trim whitespace in head
  package-lock.json
  packages/optimizer/lib/TreeParser.js
  packages/optimizer/lib/transformers/MinifyHtml.js
  packages/optimizer/package.json
  packages/optimizer/spec/end-to-end/body-only/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.valid.html
  packages/optimizer/spec/lib/TreeParserSpec.js
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_comments/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_comments/input.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_unneeded_whitespace/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/removes_unneeded_whitespace/input.html
Labels: cla: yes

#596 Add Markdown transformer
  .gitignore
  package-lock.json
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/fetchImageDimensions.js
  packages/optimizer/lib/isDependencyInstalled.js
  packages/optimizer/lib/transformers/AddBlurryImagePlaceholders.js
  packages/optimizer/lib/transformers/Markdown.js
  packages/optimizer/package.json
  packages/optimizer/spec/assets/small.jpg
  packages/optimizer/spec/end-to-end/EndToEndSpec.js
  packages/optimizer/spec/end-to-end/markdown/expected_output.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.valid.html
  packages/optimizer/spec/end-to-end/markdown/input.html
  packages/optimizer/spec/transformers/valid/Markdown/config.json
  packages/optimizer/spec/transformers/valid/Markdown/converts_img_tags/expected_output.html
  packages/optimizer/spec/transformers/valid/Markdown/converts_img_tags/input.html
Labels: cla: yes

#443 Add support for intrinsic layout
  packages/optimizer/lib/ParseLayout.js
  packages/optimizer/lib/transformers/ApplyLayout.js
  packages/optimizer/spec/transformers/experimental/ServerSideRendering/transforms_layout_intrinsic/expected_output.html
  packages/optimizer/spec/transformers/experimental/ServerSideRendering/transforms_layout_intrinsic/input.html
Labels: cla: yes
