Repository ampproject/amp-toolbox, pull requests merged in 2020-06, with the labels that each got.

#814 Move hero image preload out of experimental
  packages/cache-list/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/cors/package.json
  packages/lighthouse-plugin-amp/package.json
  packages/linter/package.json
  packages/optimizer-express/package.json
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/package.json
  packages/optimizer/spec/end-to-end/body-only/expected_output.default.html
  packages/optimizer/spec/end-to-end/body-only/expected_output.lts.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.default.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.lts.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.paired.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.default.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.lts.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/aborts_with_existing_image_preload/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/aborts_with_existing_image_preload/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_non_image_preloads/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_non_image_preloads/input.html
  packages/runtime-fetch/package.json
  packages/runtime-version/package.json
  packages/update-cache/package.json
Labels: cla: yes, enhancement, toolbox-optimizer

#828 Do not preload hero images using srcset
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset_duplicates/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset_duplicates/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/srcset_cannot_be_preloaded/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/srcset_cannot_be_preloaded/input.html
Labels: cla: yes

#826 Updated og image check to include name attr
  packages/linter/src/rules/MetadataIncludesOGImageSrc.ts
  packages/linter/tests/local.ts
  packages/linter/tests/local/MetadataIncludesOGImageSrc-3/source.html
Labels: cla: yes

#835 More robust cache warmup
  package-lock.json
  packages/optimizer/README.md
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/fetchRuntimeParameters.js
  packages/optimizer/lib/warmup.js
  packages/optimizer/package-lock.json
  packages/optimizer/package.json
Labels: cla: yes

#838 fix(optimizer): add missing dependency node-fetch
  package-lock.json
  packages/optimizer/package-lock.json
  packages/optimizer/package.json
Labels: cla: yes

#846 Fix: MinifyHtml cannot be disabled
  packages/optimizer/lib/transformers/MinifyHtml.js
Labels: cla: yes

#850 Don't remove boilerplate for amp-stories
  packages/optimizer/lib/Extensions.js
  packages/optimizer/lib/transformers/ServerSideRendering.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp-story_present/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp-story_present/input.html
Labels: bug, cla: yes, toolbox-optimizer
