Repository ampproject/amp-toolbox, pull requests merged in 2020-02, with the labels that each got.

#602 Fix typos
  packages/runtime-version/lib/RuntimeVersion.js
Labels: cla: yes

#600 optimizer: Revert unsupported self-hosting modifications
  packages/optimizer/README.md
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/RuntimeHostHelper.js
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_excludes_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_with_rtv/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_with_rtv/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_without_rtv/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_but_not_dynamic_components_without_rtv/input.html
Labels: cla: yes

#601 optimizer: Support alternate cache boilerplate CSS
  packages/optimizer/lib/transformers/AmpBoilerplateTransformer.js
  packages/runtime-version/lib/RuntimeVersion.js
Labels: cla: yes

#617 More flexible image path resolution
  packages/optimizer/lib/PathResolver.js
  packages/optimizer/lib/transformers/AddBlurryImagePlaceholders.js
  packages/optimizer/lib/transformers/Markdown.js
  packages/optimizer/spec/lib/PathResolverSpec.js
Labels: cla: yes

#626 Test explicitly for existance of value
  packages/linter/src/rules/SxgDumpSignedExchangeVerify.ts
Labels: cla: yes

#622 optimizer: Add meta tags for singleDoc self-host
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_hosts/expected_output.html
Labels: cla: yes, enhancement, toolbox-optimizer

#618 Fix: auto extension import amp-access-laterpay & amp-subscriptions-google
  package-lock.json
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-access-laterpay/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-access-laterpay/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-subscriptions/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/amp-subscriptions/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/auto-imports-missing-extensions/expected_output.html
Labels: bug, cla: yes, toolbox-optimizer
