Repository ampproject/amp-toolbox, pull requests merged in 2020-05, with the labels that each got.

#730 Add experimental image preloading support
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/parseSrcSet.js
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/spec/lib/parseSrcSetSpec.js
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-video_with_missing_poster/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-video_with_missing_poster/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/config.json
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/disable_via_param/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/disable_via_param/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/hero_image_dimensions_from_parent_container/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/hero_image_dimensions_from_parent_container/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/hero_image_dimesions_from_parent_container-_too_small/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/hero_image_dimesions_from_parent_container-_too_small/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset_duplicates/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/invalid_srcset_duplicates/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_dimension_from_parent_because_layout_is_not_responsive_or_fill/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_dimension_from_parent_because_layout_is_not_responsive_or_fill/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_dimensions_in_parent_containers/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_dimensions_in_parent_containers/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_display_layout/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/no_display_layout/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/preloads_hero_image/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/preloads_hero_image/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/same_as_above_with_nodisplay_layout_removed/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/same_as_above_with_nodisplay_layout_removed/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/srcset_validity_empty_srcset/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/srcset_validity_empty_srcset/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/video_posters/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/video_posters/input.html
Labels: cla: yes, enhancement, toolbox-optimizer

#744 WebP is okay for metadata
  package-lock.json
  package.json
  packages/linter/src/rules/StoryMetadataThumbnailsAreOk.ts
  packages/linter/tests/fixtures/thumbnails4.json
  packages/linter/tests/network.ts
Labels: cla: yes

#736 Extract runtime parameters
  packages/optimizer-express/demo/proxy.js
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/RuntimeHostHelper.js
  packages/optimizer/lib/fetchRuntimeParameters.js
  packages/optimizer/lib/transformers/AmpBoilerplateTransformer.js
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/spec/end-to-end/hello-world/input.html
  packages/optimizer/spec/helpers/TransformerRunner.js
  packages/optimizer/spec/transformers/TransformerSpec.js
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/supports_custom_host/expected_output.html
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/supports_custom_host/input.html
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/supports_lts/expected_output.html
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/supports_lts/input.html
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/uses_given_runtime_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/AmpBoilerplateTransformer/uses_given_runtime_version/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/adds_runtime_version/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/input.html
  packages/optimizer/spec/transformers/valid/AmpBoilerplateTransformer/always_inlines_v0css/expected_output.html
  packages/optimizer/spec/transformers/valid/AmpBoilerplateTransformer/always_inlines_v0css/input.html
  packages/optimizer/spec/transformers/valid/AmpBoilerplateTransformer/does_not_add_v0.css_if_style_amp-runtime_not_present/input.html
  packages/runtime-version/lib/RuntimeVersion.js
Labels: cla: yes

#752 Add missing command name to CLI documentation
  packages/optimizer/README.md
Labels: cla: yes

#753 Fix typos in parameter documentation
  packages/optimizer/lib/fetchRuntimeParameters.js
Labels: cla: yes

#757 Improve hero image preloading
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-iframe/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-iframe/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-img/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-img/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-video/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_data_uris_amp-video/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_tiny_images_intrinsic/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_tiny_images_intrinsic/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_tiny_images_responsive/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/ignores_tiny_images_responsive/input.html
Labels: cla: yes

#755 Added og:image and alt text checks to linter for Stories
  packages/linter/src/index.ts
  packages/linter/src/rules/ImagesHaveAltText.ts
  packages/linter/src/rules/MetadataIncludesOGImageSrc.ts
  packages/linter/tests/local.ts
  packages/linter/tests/local/ImagesHaveAltText-1/source.html
  packages/linter/tests/local/ImagesHaveAltText-2/source.html
  packages/linter/tests/local/MetadataIncludesOGImageSrc-1/source.html
  packages/linter/tests/local/MetadataIncludesOGImageSrc-2/source.html
Labels: cla: yes

#770 Fix postinstall failing on windows
  packages/optimizer/lib/fetchRuntimeParameters.js
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/lib/warmup.js
  packages/optimizer/package.json
  packages/optimizer/scripts/init.js
Labels: bug, cla: yes, toolbox-optimizer

#779 Linter output changes
  packages/linter/src/index.ts
  packages/linter/src/rules/StoryMetadataIsV1.ts
  packages/linter/src/rules/StoryMetadataThumbnailsAreOk.ts
Labels: cla: yes

#791 fix typo
  packages/optimizer/README.md
Labels: cla: yes

#781 Fix lts
  packages/optimizer/lib/RuntimeHostHelper.js
  packages/optimizer/lib/fetchRuntimeParameters.js
  packages/optimizer/spec/end-to-end/EndToEndSpec.js
  packages/optimizer/spec/end-to-end/body-only/expected_output.default.html
  packages/optimizer/spec/end-to-end/body-only/expected_output.lts.html
  packages/optimizer/spec/end-to-end/body-only/expected_output.paired.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.default.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.lts.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.paired.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.default.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.lts.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.paired.html
  packages/optimizer/spec/helpers/TransformerRunner.js
Labels: bug, cla: yes, toolbox-optimizer

#780 Condense linter output for image alt text check
  packages/linter/src/index.ts
  packages/linter/src/rules/ImagesHaveAltText.ts
  packages/linter/src/rules/StoryMetadataThumbnailsAreOk.ts
Labels: cla: yes

#795 Added video subtitle and alt text checks
  packages/linter/src/index.ts
  packages/linter/src/rules/VideosAreSubtitled.ts
  packages/linter/src/rules/VideosHaveAltText.ts
  packages/linter/tests/local.ts
  packages/linter/tests/local/VideosAreSubtitled-1/source.html
  packages/linter/tests/local/VideosAreSubtitled-2/source.html
  packages/linter/tests/local/VideosHaveAltText-1/source.html
  packages/linter/tests/local/VideosHaveAltText-2/source.html
Labels: cla: yes

#799 [optimizer] add missing runtime dependencies
  package-lock.json
  package.json
  packages/core/package.json
  packages/optimizer/lib/TreeParser.js
  packages/optimizer/package.json
Labels: bug, cla: yes, toolbox-optimizer

#802 fix: add missing dependencies
  package-lock.json
  packages/cli/package.json
  packages/optimizer/package.json
Labels: cla: yes

#772 add srcset transformer
  lerna.json
  package-lock.json
  package.json
  packages/cli/package.json
  packages/linter/package.json
  packages/optimizer-express/package.json
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/lib/URLUtils.js
  packages/optimizer/lib/image-optimizers/simpleRename.js
  packages/optimizer/lib/transformers/OptimizeImages.js
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/lib/transformers/PreloadImages.js
  packages/optimizer/package-lock.json
  packages/optimizer/package.json
  packages/optimizer/spec/transformers/TransformerSpec.js
  packages/optimizer/spec/transformers/valid/OptimizeImages/adds_srcset/expected_output.html
  packages/optimizer/spec/transformers/valid/OptimizeImages/adds_srcset/input.html
Labels: cla: yes, enhancement, toolbox-optimizer

#805 Support media attribute for hero image preloading
  packages/optimizer/README.md
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-img/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-img/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-video_with_poster/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/amp-video_with_poster/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-iframe/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-iframe/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-img/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-img/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-video-iframe/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-video-iframe/input.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-video/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/media_attribute_amp-video/input.html
Labels: cla: yes, enhancement, toolbox-optimizer

#807 List all supported options in README
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/AddMandatoryTags.js
Labels: cla: yes, enhancement, toolbox-optimizer

#810 Fix id generation
  packages/optimizer/lib/transformers/ApplyCommonAttributes.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_media_attribute_to_css/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_sizes_attribute_to_css/expected_output.html
Labels: cla: yes

#811 fix child selector
  packages/optimizer/lib/transformers/ApplyCommonAttributes.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_heights_attribute_to_css/expected_output.html
Labels: cla: yes

#806 Sort linter output
  packages/cli/lib/cmds/lint.js
  packages/linter/src/cli.ts
  packages/linter/src/index.ts
  packages/linter/src/rules/ImagesHaveAltText.ts
Labels: cla: yes
