Repository ampproject/amp-toolbox, pull requests merged in 2020-03, with the labels that each got.

#648 update dependencies
  package-lock.json
  package.json
  packages/cli/package.json
  packages/cli/spec/ioSpec.js
  packages/lighthouse-plugin-amp/package.json
  packages/linter/package.json
  packages/optimizer/package.json
Labels: cla: yes, internal

#649 Encode JSON values
  packages/optimizer/lib/htmlEscape.js
  packages/optimizer/lib/transformers/MinifyHtml.js
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/expected_output.html
  packages/optimizer/spec/transformers/valid/MinifyHtml/minifies_inline_JSON/input.html
Labels: bug, cla: yes, toolbox-optimizer

#656 Fix linter README
  packages/linter/README.md
Labels: cla: yes

#653 Don't separate keyframes for AMP Stories
  packages/optimizer/lib/transformers/SeparateKeyframes.js
  packages/optimizer/spec/transformers/valid/SeparateKeyframes/ignores_amp_stories/expected_output.html
  packages/optimizer/spec/transformers/valid/SeparateKeyframes/ignores_amp_stories/input.html
  packages/optimizer/spec/transformers/valid/SeparateKeyframes/moves_keyframes/input.html
Labels: bug, cla: yes, toolbox-optimizer

#662 cache-list: Update caches example in readme
  packages/cache-list/README.md
Labels: cla: yes

#636 optimizer: Output amp-geo API meta tags
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.html
  packages/optimizer/spec/end-to-end/hello-world/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/adds_geoapi/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/adds_geoapi/input.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_host_and_adds_version/expected_output.html
  packages/optimizer/spec/transformers/experimental/RewriteAmpUrls/rewrites_hosts/expected_output.html
Labels: cla: yes, enhancement

#669 Fix typo in README.md
  packages/optimizer/demo/markdown/README.md
Labels: cla: yes

#664 Update eslint config
  .eslintrc.json
  packages/.eslintrc.json
  packages/cache-url/lib/browser/Sha256.js
  packages/cache-url/spec/AmpUrlSpec.js
  packages/cors/spec/lib/corsSpec.js
Labels: cla: yes

#673 optimizer: Remove extraneous troublesome file
  packages/optimizer/spec/transformers/valid/ServerSideRendering/boilerplate_not_removed_when_amp_experiment_present/input.html /input.html
Labels: cla: yes

#666 Update CURLs hasing algorithm
  package-lock.json
  packages/cache-url/lib/AmpCurlUrlGenerator.js
  packages/cache-url/spec/AmpUrlSpec.js
  packages/cli/spec/cmds/curlsSpec.js
Labels: cla: yes, enhancement
