Repository ampproject/amp-toolbox, pull requests merged in 2020-08, with the labels that each got.

#883 Keep nonces
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.default.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.lts.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.paired.html
  packages/optimizer/spec/end-to-end/hello-world/input.html
  packages/optimizer/spec/valid-amp/files/_Hello_World.html
Labels: cla: yes

#887 Fix NPE during SSR when style block is empty
  packages/optimizer/lib/transformers/ApplyCommonAttributes.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/empty_custom_styles/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/empty_custom_styles/input.html
Labels: cla: yes

#886 docs: Improves code snippets readability
  packages/optimizer/README.md
Labels: cla: yes

#889 add linter demo
  packages/linter/demo/index.js
  packages/optimizer/spec/end-to-end/hello-world/expected_output.default.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.lts.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.paired.html
  packages/optimizer/spec/end-to-end/hello-world/input.html
Labels: cla: yes

#890 introduce pageexperience mode
  packages/linter/src/cli.ts
  packages/linter/src/index.ts
Labels: cla: yes, enhancement, toolbox-linter

#891 Small README fixed
  packages/optimizer/README.md
Labels: cla: yes

#892 Small README fixes
  packages/optimizer/README.md
Labels: cla: yes, documentation

#893 update dependencies
  package-lock.json
  package.json
  packages/lighthouse-plugin-amp/package.json
  packages/linter/package.json
  packages/optimizer/package.json
  packages/optimizer/spec/transformers/valid/PreloadHeroImage/srcset_validity_empty_srcset/expected_output.html
  packages/optimizer/spec/transformers/valid/PreloadImages/skips_images_inside_templates/expected_output.html
  packages/update-cache/package.json
Labels: cla: yes, internal

#896 Don't ssr amp-img in stories
  packages/optimizer/lib/AmpConstants.js
  packages/optimizer/lib/transformers/PreloadHeroImage.js
  packages/optimizer/spec/end-to-end/story/expected_output.default.html
  packages/optimizer/spec/end-to-end/story/expected_output.lts.html
  packages/optimizer/spec/end-to-end/story/expected_output.paired.html
  packages/optimizer/spec/end-to-end/story/input.html
  packages/optimizer/spec/helpers/TransformerRunner.js
Labels: bug, cla: yes, toolbox-optimizer

#895 Using jest for linter
  .gitignore
  README.md
  jest.config.js
  package-lock.json
  package.json
  packages/linter/README.md
  packages/linter/package.json
  packages/linter/tests/helper.test.ts
  packages/linter/tests/helper.ts
  packages/linter/tests/lib.ts
  packages/linter/tests/local.test.ts
  packages/linter/tests/local.ts
  packages/linter/tests/network.test.ts
  packages/linter/tests/network.ts
Labels: cla: yes, internal, toolbox-linter

#900 fix README.md
  packages/optimizer/README.md
Labels: cla: yes

#901 Feature/linter optimizer checks
  packages/linter/src/helper.ts
  packages/linter/src/index.ts
  packages/linter/src/rules/IsTransformedAmp.ts
  packages/linter/src/rules/ModuleRuntimeUsed.ts
  packages/linter/tests/helper.test.ts
  packages/linter/tests/local.test.ts
  packages/linter/tests/local/IsTransformedAmp-1/source.html
  packages/linter/tests/local/IsTransformedAmp-2/source.html
  packages/linter/tests/local/ModuleRuntimeUsed-1/source.html
  packages/linter/tests/local/ModuleRuntimeUsed-2/source.html
Labels: cla: yes, enhancement, toolbox-linter

#899 Make AMP Toolbox build on windows
  .eslintrc.json
  .gitattributes
  .github/workflows/CI.yml
  .travis.yml
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  packages/cache-url/index.d.ts
  packages/cache-url/lib/AmpCurlUrlGenerator.js
  packages/cache-url/rollup.config.js
  packages/cli/lib/cli.js
  packages/cli/lib/cmds/downloadRuntime.js
  packages/cli/lib/io.js
  packages/cli/spec/ioSpec.js
  packages/cors/lib/cors.js
  packages/cors/spec/lib/corsSpec.js
  packages/linter/package.json
  packages/linter/src/cli.ts
  packages/linter/tsconfig.json
  packages/optimizer/demo/express/app.js
  packages/optimizer/demo/gulp/gulpfile.js
  packages/optimizer/lib/fetchRuntimeParameters.js
  packages/optimizer/lib/parseSizes.js
  packages/optimizer/lib/parseSrcSet.js
  packages/optimizer/lib/transformers/AmpBoilerplateTransformer.js
  packages/optimizer/lib/transformers/ApplyLayout.js
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/lib/transformers/OptimizeImages.js
  packages/optimizer/lib/transformers/RewriteAmpUrls.js
  packages/optimizer/lib/warmup.js
  packages/runtime-fetch/lib/DownloadRuntime.js
  packages/runtime-version/lib/RuntimeVersion.js
  tsconfig.json
Labels: cla: yes, internal

#902 Preload checks for blocking extensions
  packages/linter/src/index.ts
  packages/linter/src/rules/BlockingExtensionsPreloaded.ts
  packages/linter/src/rules/RuntimeIsPreloaded.ts
  packages/linter/tests/local.test.ts
  packages/linter/tests/local/BlockingExtensionsPreloaded-1/source.html
  packages/linter/tests/local/BlockingExtensionsPreloaded-2/source.html
  packages/linter/tests/local/BlockingExtensionsPreloaded-3/source.html
  packages/linter/tests/local/RuntimeIsPreloaded-3/source.html
Labels: cla: yes, enhancement, toolbox-linter

#903 ensure to run build before publish
  package.json
Labels: cla: yes

#907 Linter rule for Google Font preconnect
  packages/linter/src/index.ts
  packages/linter/src/rules/FastGoogleFontsDisplay.ts
  packages/linter/src/rules/GoogleFontPreconnect.ts
  packages/linter/tests/local.test.ts
  packages/linter/tests/local/GoogleFontPreconnect-1/source.html
  packages/linter/tests/local/GoogleFontPreconnect-2/source.html
  packages/linter/tests/local/GoogleFontPreconnect-3/source.html
Labels: cla: yes, enhancement, toolbox-linter

#908 Linter rule for AMP Boilerplate removal
  packages/linter/src/index.ts
  packages/linter/src/rules/BoilerplateIsRemoved.ts
  packages/linter/tests/local.test.ts
  packages/linter/tests/local/BoilerplateIsRemoved-1/source.html
  packages/linter/tests/local/BoilerplateIsRemoved-2/source.html
  packages/linter/tests/local/BoilerplateIsRemoved-3/source.html
  packages/linter/tests/local/BoilerplateIsRemoved-4/source.html
  packages/linter/tests/local/BoilerplateIsRemoved-5/source.html
Labels: cla: yes, enhancement, toolbox-linter

#911 Allow users to specify version numbers for auto imported extensions
  packages/optimizer/README.md
  packages/optimizer/lib/transformers/AutoExtensionImporter.js
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/allow-specific-version/expected_output.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/allow-specific-version/input.html
  packages/optimizer/spec/transformers/valid/AutoExtensionImporter/config.json
Labels: cla: yes, enhancement, toolbox-optimizer

#909 Fix handling of malformed `sizes` and `heights` strings
  packages/optimizer/lib/parseSizes.js
  packages/optimizer/spec/lib/parseSizesSpec.js
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_heights_attribute_to_css/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_heights_attribute_to_css/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_sizes_attribute_to_css/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/converts_sizes_attribute_to_css/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_apply_transformations_if_already_present/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_apply_transformations_if_already_present/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_heights_attribute/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_heights_attribute/input.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_sizes_attribute/expected_output.html
  packages/optimizer/spec/transformers/valid/ServerSideRendering/does_not_convert_invalid_sizes_attribute/input.html
Labels: bug, cla: yes, toolbox-optimizer
