Repository ampproject/amp-toolbox, pull requests merged in 2021-03, with the labels that each got.

#1166 Move result details to top level
  packages/page-experience/lib/PageExperienceGuide.js
  packages/page-experience/lib/checks/fontDisplay.js
  packages/page-experience/lib/checks/fontPreloading.js
  packages/page-experience/test-data/checks/fontDisplay/font-display-optional.json
  packages/page-experience/test-data/checks/fontDisplay/font-display-swap-google-fonts.json
  packages/page-experience/test-data/checks/fontDisplay/font-display-swap-non-critical.json
  packages/page-experience/test-data/checks/fontDisplay/font-display-swap.json
  packages/page-experience/test-data/checks/fontDisplay/missing-fontface-is-ignored.json
  packages/page-experience/test-data/checks/fontDisplay/no-font-display-non-critical.json
  packages/page-experience/test-data/checks/fontDisplay/no-font-display.json
  packages/page-experience/test-data/checks/fontPreloading/critical-font-not-preloaded.json
  packages/page-experience/test-data/checks/fontPreloading/critical-font-preloaded.json
  packages/page-experience/test-data/checks/fontPreloading/google-font.json
  packages/page-experience/test-data/checks/fontPreloading/non-critical-font-not-preloaded.json
  packages/page-experience/test-data/checks/fontPreloading/non-critical-font-preloaded.json
Labels: bug

#1169 Give page specific advice on how to fix fonts
  packages/page-experience/lib/checks/fontDisplay.js
  packages/page-experience/lib/checks/fontPreloading.js
Labels: enhancement

#1168 Check for early iframes
  packages/page-experience/lib/PageDataGatherer.js
  packages/page-experience/lib/checks/earlyIframes.js
  packages/page-experience/test-data/checks/earlyIframes/iframe-in-first-viewport.html
  packages/page-experience/test-data/checks/earlyIframes/iframe-in-first-viewport.json
  packages/page-experience/test-data/checks/earlyIframes/iframe-outside-first-viewport.html
  packages/page-experience/test-data/checks/earlyIframes/iframe-outside-first-viewport.json
Labels: enhancement

#1172 PX: escape html in suggestions
  packages/page-experience/lib/checks/earlyIframes.js
  packages/page-experience/lib/checks/heroImages.js
  packages/page-experience/test-data/checks/earlyIframes/iframe-in-first-viewport.json
  packages/page-experience/test-data/checks/heroImages/image-in-first-viewport.json
Labels: enhancement

#1174 PX: enable mobile device emulation
  CHANGELOG.md
  lerna.json
  packages/page-experience/bin/cli.js
  packages/page-experience/lib/PageDataGatherer.js
  packages/page-experience/lib/PageExperienceGuide.js
  packages/page-experience/lib/checks/heroImages.js
  packages/page-experience/package-lock.json
  packages/page-experience/package.json
Labels: enhancement

#1184 Remove hard-coded isTiny() result for intrinsic layout
  packages/optimizer/lib/transformers/OptimizeHeroImages.js
  packages/optimizer/spec/transformers/valid/OptimizeHeroImages/ignores_tiny_images_intrinsic/expected_output.html
Labels: bug, toolbox-optimizer

#1180 Add minimal Optimizer Transformer Config
  package-lock.json
  packages/optimizer/demo/benchmark/index.js
  packages/optimizer/demo/benchmark/package-lock.json
  packages/optimizer/demo/benchmark/package.json
  packages/optimizer/demo/benchmark/samples/amp.dev.html
  packages/optimizer/index.js
  packages/optimizer/lib/DomTransformer.js
  packages/optimizer/package-lock.json
  packages/optimizer/spec/end-to-end/EndToEndSpec.js
  packages/optimizer/spec/end-to-end/body-only/expected_output.minimal.html
  packages/optimizer/spec/end-to-end/hello-world/expected_output.minimal.html
  packages/optimizer/spec/end-to-end/markdown/expected_output.minimal.html
  packages/optimizer/spec/end-to-end/story/expected_output.minimal.html
  packages/optimizer/spec/end-to-end/trailing-template/expected_output.minimal.html
Labels: enhancement, toolbox-optimizer
